[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://tsyowtatzuxbvquhkgyo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeW93dGF0enV4YnZxdWhrZ3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODI3MjYsImV4cCI6MjA2ODY1ODcyNn0.WY-Ly-k9zrP7vEvefKKLsatd1RPfS9Txo3sKBiDxPTY"
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyB-kT4aRY_THYT8Am33VdP21nkwLaR6O8Q"