-- Enable extensions
create extension if not exists "postgis" with schema "public";
create extension if not exists "tablefunc" with schema "public";

-- Define custom types
create type "public"."incident_type" as enum ('Theft', 'Assault', 'Vandalism', 'Harassment', 'Robbery', 'Burglary', 'Fire', 'Medical Emergency', 'Suspicious Activity', 'Environmental Hazard', 'Road Accident', 'Other');
create type "public"."report_status" as enum ('pending_verification', 'verified', 'rejected', 'archived', 'resolved');
create type "public"."user_role" as enum ('admin', 'authority');

-- Create tables
create table "public"."jurisdiction_boundaries" (
    "id" bigint generated by default as identity not null,
    "psgc_code" text not null,
    "barangay_name" text,
    "city_name" text,
    "geom" geometry(MultiPolygon,4326),
    constraint "jurisdiction_boundaries_pkey" primary key (id),
    constraint "jurisdiction_boundaries_psgc_code_key" unique (psgc_code)
);
create index sidx_jurisdiction_boundaries_geom ON public.jurisdiction_boundaries USING gist (geom);

create table "public"."users" (
    "id" uuid not null,
    "email" text not null,
    "role" user_role,
    "jurisdiction" text,
    "created_at" timestamp with time zone default now(),
    "onboarding_completed" boolean default false,
    constraint "users_pkey" primary key (id),
    constraint "users_email_key" unique (email),
    constraint "users_id_fkey" foreign key (id) references auth.users(id) on delete cascade,
    constraint "admin_cannot_have_jurisdiction" check (not ((role = 'admin'::user_role) and (jurisdiction is not null)))
);

create table "public"."reports" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid,
    "location" jsonb,
    "incident_type" public.incident_type,
    "severity" text,
    "description" text,
    "image_path" text,
    "status" public.report_status default 'pending_verification'::report_status,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "verified_by" uuid,
    "verified_at" timestamp with time zone,
    "tracking_code" text,
    "jurisdiction" text,
    "is_flagged" boolean default false,
    "contact_info" text,
    "notes" text,
    "incident_type_other" text,
    constraint "reports_pkey" primary key (id),
    constraint "reports_tracking_code_key" unique (tracking_code),
    constraint "reports_user_id_fkey" foreign key (user_id) references users(id) on delete set null,
    constraint "reports_verified_by_fkey" foreign key (verified_by) references users(id) on delete set null,
    constraint "incident_type_other_check" check ((((incident_type = 'Other'::public.incident_type) and (incident_type_other is not null) and (incident_type_other <> ''::text)) or ((incident_type <> 'Other'::public.incident_type) and (incident_type_other is null))))
);

-- Create a trigger to automatically create a user profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public as $$
begin
  insert into public.users (id, email, role, jurisdiction)
  values (new.id, new.email, (new.raw_user_meta_data->>'role')::public.user_role, (new.raw_user_meta_data->>'jurisdiction'));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create SQL Functions (RPCs)
CREATE OR REPLACE FUNCTION public.get_jurisdiction_for_location(location_data jsonb)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT psgc_code FROM public.jurisdiction_boundaries
  WHERE ST_Intersects(geom, ST_SetSRID(ST_MakePoint((location_data->>'lng')::double precision, (location_data->>'lat')::double precision), 4326))
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_report_stats()
RETURNS TABLE(status report_status, count bigint) LANGUAGE sql SECURITY INVOKER AS $$
    SELECT r.status, COUNT(r.id) FROM public.reports r GROUP BY r.status;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_user_stats()
RETURNS TABLE(role user_role, count bigint) LANGUAGE sql SECURITY INVOKER AS $$
    SELECT u.role, COUNT(u.id) FROM public.users u GROUP BY u.role;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_top_jurisdictions()
RETURNS TABLE(jurisdiction_name text, count bigint) LANGUAGE sql SECURITY INVOKER AS $$
  SELECT j.barangay_name || ', ' || j.city_name as jurisdiction_name, COUNT(r.id) as count
  FROM public.reports AS r JOIN public.jurisdiction_boundaries j ON r.jurisdiction = j.psgc_code
  WHERE r.jurisdiction IS NOT NULL
  GROUP BY j.barangay_name, j.city_name
  ORDER BY count DESC
  LIMIT 10;
$$;

CREATE OR REPLACE FUNCTION public.get_reports_for_authority()
RETURNS SETOF reports LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
  user_jurisdiction TEXT;
BEGIN
  SELECT jurisdiction INTO user_jurisdiction
  FROM public.users
  WHERE id = auth.uid() AND role = 'authority';
  IF user_jurisdiction IS NULL THEN
    RAISE EXCEPTION 'User is not an authorized authority or does not have a jurisdiction.';
  END IF;
  RETURN QUERY
  SELECT * FROM public.reports
  WHERE jurisdiction = user_jurisdiction
  ORDER BY created_at DESC
  LIMIT 50;
END;
$$;

-- Enable RLS on all tables
alter table "public"."reports" enable row level security;
alter table "public"."users" enable row level security;
alter table "public"."jurisdiction_boundaries" enable row level security;

-- RLS Policies
CREATE POLICY "Allow public read access to boundaries" ON public.jurisdiction_boundaries FOR SELECT USING (true);
CREATE POLICY "Allow users to view their own profile" ON "public"."users" FOR SELECT TO authenticated USING ((auth.uid() = id));
CREATE POLICY "Allow admins full access to users" ON "public"."users" FOR ALL TO authenticated USING (((SELECT role FROM public.users WHERE id = auth.uid()) = 'admin')) WITH CHECK (((SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'));
CREATE POLICY "Allow anonymous report creation" ON "public"."reports" FOR INSERT TO public WITH CHECK (true);
-- Note: SELECT/UPDATE/DELETE on reports is now handled by the secure RPC functions, not direct RLS policies for users.